### ISSUE TITLE
Generic Workflow to create and Publish Docker images. 

### ISSUE THREAD

**Issue by shailesh-vaidya** [Seagate/cortx-re#27]
We can use [base-docker-image ](https://github.com/Seagate/cortx-re/blob/github-action-work/.github/workflows/base-docker-image.yml) workflow to generate Docker Images. It takes most of the parameters as variables so can be easily scaled to build Docker images for other components. 

Workflow details are as below. 

 ```
steps:
    - uses: actions/checkout@v2
    - name: Set ENV
      run: |
        echo ::set-env name=INPUT_REPOSITORY::$( echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
        echo ::set-env name=IMAGE_NAME::cortx_centos
        echo ::set-env name=TAG::7.7.1908
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      env:
          DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
          REPO_NAME: ${{ github.event.repository.name }}
      with:
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        dockerfile: docker/cortx_components/centos/Dockerfile 
        # Build Arguments for docker image build. 
        build_args: 'CENTOS_RELEASE=7.7.1908,USER_PASS=root:"$DEFAULT_PASSWORD"'
        path: docker/cortx_components/centos/
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ env.INPUT_REPOSITORY }}/${{ env.IMAGE_NAME }}
        tags: ${{ env.TAG }}
```
